name: Generate Snake

on:
  # 每 24 小时自动运行一次 (每天凌晨 0 点)
  schedule:
    - cron: "0 0 * * *" 
  
  # 允许在 Actions 页面手动触发执行
  workflow_dispatch:
  
  # 每次 push 到 main 分支时运行
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # 第一步：生成贪吃蛇动画
      - name: generate-snake-game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa

      # 第二步：将生成的图片推送到 output 分支
      # 这会让你的 main 分支保持整洁，图片单独存放在 output 分支
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
